"""WSL2 VLM Model Server Client - WSL2 Container Controller.

SYSTEM ROLE & ARCHITECTURE:
This module serves as the cross-platform execution bridge between the Windows host environment 
and the Docker container running inside WSL2. It enables the local orchestrator to control 
the Linux-based GPU vision-language model (VLM) server and transfer image data seamlessly.

                 +-------------------------------------------------+
                 |                  Windows Host                   |
                 |  +--------------------+  +-------------------+  |
                 |  | describe_photos.py |  |   wsl_client.py   |  |
                 |  +--------------------+  +---------+---------+  |
                 +------------------------------------|------------+
                                                      | (spawns cmd)
                                                      v
                                            +---------v---------+
                                            | WSL2 CLI Interface|
                                            +---------+---------+
                                                      | (docker control)
                                                      v
     +------------------------------------------------v--------------------+
     |                        WSL2 Docker Environment                      |
     |  +---------------------------------------------------------------+  |
     |  |                 Container: trt_llm_build                      |  |
     |  |  +-----------------------+           +---------------------+  |  |
     |  |  |  wsl_server.py (API)  | <=======> | Gemma 4 12B IT (GPU)|  |  |
     |  |  +-----------------------+           +---------------------+  |  |
     |  +---------------------------------------------------------------+  |
     +---------------------------------------------------------------------+

EXECUTION WORKFLOW:
1. Command Prefix Generation: Formulates standard WSL command blocks (e.g., `['wsl', '-u', 'username']`) 
   to execute commands inside the default WSL2 Linux distribution.
2. Container Lifecycle Management:
   - Starts the target Docker container (`docker start trt_llm_build`).
   - Polls for directory mount readiness inside the container (verifies `/workspace` directory mount 
     before starting the application server).
   - Stops the container to free GPU VRAM once operations are finished.
3. Server Launch: If the FastAPI microservice is not already running inside the container, 
   spawns uvicorn in the background using `docker exec -d` with appropriate environment variables 
   (e.g., `LD_LIBRARY_PATH` and CUDA bindings).
4. GPU Load Verification: Polls the server documents page over HTTP until the server reports 
   alive (which happens after VLM weights are loaded into VRAM, taking up to 7.5 minutes).
5. Payload Dispatch: Encodes batches of images into Base64 JPEG strings and posts them to 
   the `/describe` HTTP REST endpoint.

INPUTS:
- Image paths or pre-encoded base64 strings.
- Prompt text instructions.
- Environment variables: `VLM_SERVER_URL`, `VLM_CONTAINER_NAME`, `WSL_USER`.

OUTPUTS:
- Status indicators (boolean results for start/health checks).
- List of raw JSON-formatted string outputs generated by the VLM.

CRITICAL DEPENDENCIES:
- WSL2 subsystem enabled on Windows.
- Docker engine configured and running within WSL2.
- `requests` and `pillow-heif` modules installed locally on the host.

AGENT GUIDELINE FOR MODIFICATION:
- Subprocess executions (`subprocess.run`) must not use `shell=True` to prevent tokenization/quoting 
  issues between Windows CMD/PowerShell and WSL2 Linux bash.
- Ensure that network timeouts (`requests.post(..., timeout=180.0)`) are set generously to allow 
  for large multi-image batch vision processing.
"""

import os
import sys
import subprocess
import base64
import io
import time
import logging
from typing import List, Dict, Optional, Any

import requests
from PIL import Image, ImageFile
Image.MAX_IMAGE_PIXELS = None  # Disable limit to allow massive upscaled images
ImageFile.LOAD_TRUNCATED_IMAGES = True  # Allow reading truncated or slightly corrupted files
import pillow_heif
pillow_heif.register_heif_opener()

logger = logging.getLogger(__name__)

# Load dotenv if available to manage configuration variables
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Load configurations from environment variables
SERVER_URL: str = os.environ.get("VLM_SERVER_URL", "http://127.0.0.1:8000/describe")
HEALTH_URL: str = os.environ.get("VLM_HEALTH_URL", "http://127.0.0.1:8000/docs")
CONTAINER_NAME: str = os.environ.get("VLM_CONTAINER_NAME", "trt_llm_build")
WSL_USER: str = os.environ.get("WSL_USER", "workbench")


def get_wsl_base_cmd() -> List[str]:
    """Generates the command prefix for invoking commands inside WSL2.

    Returns:
        A list of command prefix arguments (e.g. ["wsl", "-u", "workbench"]).
    """
    if WSL_USER:
        return ["wsl", "-u", WSL_USER]
    return ["wsl"]


def is_server_alive() -> bool:
    """Checks if the FastAPI server is running and responding on port 8000.

    Returns:
        True if alive, False otherwise.
    """
    try:
        response = requests.head(HEALTH_URL, timeout=1.0)
        return response.status_code == 200
    except requests.RequestException:
        return False


def is_uvicorn_running() -> bool:
    """Checks if the uvicorn process is already running inside the Docker container.

    Returns:
        True if the uvicorn process is active, False otherwise.
    """
    cmd = get_wsl_base_cmd() + ["docker", "exec", CONTAINER_NAME, "pgrep", "-f", "uvicorn"]
    try:
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True
        )
        return len(result.stdout.strip()) > 0
    except subprocess.CalledProcessError:
        return False


def start_wsl_server() -> bool:
    """Spins up the WSL2 Docker container and starts the FastAPI VLM server.

    Returns:
        True if the server is successfully running and ready, False otherwise.
    """
    logger.info("Starting WSL2 model server...")
    
    # Start the Docker container
    try:
        logger.info(f"Ensuring container '{CONTAINER_NAME}' is running...")
        start_cmd = get_wsl_base_cmd() + ["docker", "start", CONTAINER_NAME]
        subprocess.run(start_cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        
        # Wait for container volume mounts to be fully attached (up to 10 seconds)
        mount_ready = False
        check_mount_cmd = get_wsl_base_cmd() + ["docker", "exec", CONTAINER_NAME, "test", "-d", "/workspace"]
        for _ in range(10):
            res = subprocess.run(check_mount_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if res.returncode == 0:
                mount_ready = True
                break
            time.sleep(1.0)
            
        if not mount_ready:
            logger.error("Timeout: /workspace mount was not mounted in time inside container.")
            return False
            
    except subprocess.CalledProcessError as e:
        err_msg = e.stderr.decode().strip() if e.stderr else str(e)
        logger.error(f"Failed to start docker container {CONTAINER_NAME}: {err_msg}")
        return False

    # Check if uvicorn is already running. If not, launch it.
    if is_uvicorn_running():
        logger.info("Uvicorn is already running inside the container. Bypassing launch command.")
    else:
        # Start uvicorn server in the background inside the container
        cmd = get_wsl_base_cmd() + [
            "docker", "exec", "-d", "-w", "/workspace",
            "-e", "LD_LIBRARY_PATH=/usr/local/tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
            "-e", "BNB_CUDA_VERSION=130",
            "-e", "TQDM_DISABLE=1",
            "-e", "HF_HUB_DISABLE_PROGRESS_BARS=1",
            CONTAINER_NAME,
            "uvicorn", "local.wsl_server:app", "--host", "0.0.0.0", "--port", "8000"
        ]
        try:
            logger.info("Launching FastAPI server inside container...")
            subprocess.run(cmd, check=True)
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to launch uvicorn inside container: {e}")
            return False

    # Poll the server until it finishes loading the weights
    max_attempts = 150
    logger.info("Waiting for Gemma 4 VLM weights to load into VRAM...")
    for attempt in range(1, max_attempts + 1):
        if is_server_alive():
            logger.info("WSL2 Model Server is active and listening on port 8000!")
            return True
        time.sleep(3.0)
        if attempt % 5 == 0:
            logger.info(f"Still waiting for model loading... (Attempt {attempt}/{max_attempts})")

    logger.error("Timeout: WSL2 model server failed to start within 7.5 minutes.")
    return False


def stop_wsl_server() -> None:
    """Stops the Docker container inside WSL2, releasing all GPU VRAM.

    Returns:
        None
    """
    logger.info("Shutting down WSL2 model server container...")
    cmd = get_wsl_base_cmd() + ["docker", "stop", CONTAINER_NAME]
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        logger.info("WSL2 model server container stopped successfully. VRAM released.")
    except Exception as e:
        logger.warning(f"Failed to stop docker container {CONTAINER_NAME}: {e}")


def query_vlm_server(image_paths: List[str], prompt_text: str) -> List[str]:
    """Encodes a batch of images to Base64 JPEGs and queries the VLM REST server.

    Args:
        image_paths: List of absolute file paths to the images.
        prompt_text: The instructions prompt text to send.

    Returns:
        A list of raw response strings containing the model's generated JSON.

    Raises:
        RuntimeError: If connection or inference requests fail.
    """
    images_base64: List[str] = []
    for path in image_paths:
        try:
            img = Image.open(path).convert("RGB")
            buffered = io.BytesIO()
            img.save(buffered, format="JPEG", quality=90)
            img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
            images_base64.append(img_str)
        except Exception as e:
            raise RuntimeError(f"Failed to read/encode image {path}: {e}")

    return query_vlm_server_base64(images_base64, prompt_text)


def query_vlm_server_base64(images_base64: List[str], prompt_text: str) -> List[str]:
    """Queries the VLM REST server directly with pre-encoded Base64 image strings.

    Args:
        images_base64: List of base64 encoded image strings.
        prompt_text: The instructions prompt text to send.

    Returns:
        A list of raw response strings containing the model's generated JSON.

    Raises:
        RuntimeError: If connection or inference requests fail.
    """
    payload: Dict[str, Any] = {
        "images_base64": images_base64,
        "prompt_text": prompt_text
    }
    
    try:
        response = requests.post(SERVER_URL, json=payload, timeout=180.0)
        if response.status_code == 200:
            return response.json().get("raw_responses", [])
        else:
            raise RuntimeError(f"Server returned HTTP error {response.status_code}: {response.text}")
    except requests.RequestException as e:
        raise RuntimeError(f"Failed to connect to model server: {e}")
