"""Metadata embedding utility using ExifTool - Bulk EXIF Embedder.

SYSTEM ROLE & ARCHITECTURE:
This module is a post-processing utility used by the Local VLM pipeline. It performs 
high-performance bulk operations to natively embed text descriptions (generated by VLMs) 
into EXIF, IPTC, and XMP metadata fields inside raw photo files.

For cloud-based pipelines (Vertex AI / Gemini API), see the separate public repository at:
https://github.com/smichalove/Gemini_Photo_Batch_Workflow

                                 +--------------------+
                                 |  photo_desc.json   |
                                 +---------+----------+
                                           | (reads database)
                                           v
                                 +---------v----------+
                                 |  embed_metadata.py |
                                 +---------+----------+
                                           | (filters with)
                                           v
                                 +---------v----------+
                                 |  embedded_cache.txt|
                                 +---------+----------+
                                           |
                                           | (chunks into batches of 200)
                                           v
                                 +---------v----------+
                                 | ExifTool Executable|
                                 | (writes bulk JSON) |
                                 +---------+----------+
                                           |
                       +-------------------+-------------------+
                       | (success)                             | (fails)
                       v                                       v
             +---------v----------+                  +---------v----------+
             | Write cache file   |                  | Fallback to single |
             | (IPTC/EXIF/XMP ok) |                  | (exiftool -m item) |
             +--------------------+                  +--------------------+

EXECUTION WORKFLOW:
1. Path Normalization & Cache Filtering: Reads the main JSON database, normalizes paths to 
   lowercase forward slashes, and checks them against `embedded_photos_cache.txt` to process 
   only new entries.
2. Chunking: Groups unprocessed records into batches (default size 200) to maximize filesystem 
   and process startup efficiency.
3. Batch Processing: Writes a temporary JSON configuration map linking local paths to 
   description texts. Runs ExifTool using the `-j` json-import option to update the batch in 
   a single execution (drastically faster than spawning a process per file).
4. Error Isolation & Recovery: If ExifTool reports a failure or warning on the batch, the script 
   falls back to processing that batch's files individually (`update_metadata_single`):
   - Bad Photoshop IRB: Strips Photoshop IRB resource sections and retries.
   - Lock Files: Cleans up orphaned `_exiftool_tmp` files and retries.
   - Corrupt files: Skips and marks them to prevent execution hangs.
5. Cache Logging: Appends successfully embedded file paths to the cache file under a thread Lock.

INPUTS:
- photo_descriptions.json: Structured VLM output database.
- environment variables: `OUTPUT_DATABASE_PATH`, `EMBEDDED_CACHE_PATH`, `EXIFTOOL_PATH`, 
  `CHUNK_SIZE`, `MAX_WORKERS`.

OUTPUTS:
- Directly writes IPTC (Caption-Abstract), EXIF (ImageDescription), and XMP (Description) tags.
- Appends success paths to `embedded_photos_cache.txt`.

CRITICAL DEPENDENCIES:
- ExifTool CLI executable must be available on the path or configured via environment variables.

AGENT GUIDELINE FOR MODIFICATION:
- In the JSON data file passed to ExifTool, path keys ("SourceFile") must use forward-slash 
  separators (e.g. `C:/Photos/image.jpg`) even on Windows. Using backslashes will prevent 
  ExifTool from matching the import record to the physical file.
- Keep the `cache_lock` active during concurrent file updates to avoid file write pointer conflicts.
"""

import os
import sys
import json
import subprocess
import concurrent.futures
import threading
import uuid
from typing import List, Dict, Set, Tuple, Optional, Union

# Ensure standard output and error streams handle UTF-8 on Windows
if sys.platform == 'win32':
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except AttributeError:
        pass

# Load dotenv if available to manage configuration variables
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Retrieve configuration from environment variables with sensible defaults
OUTPUT_DATABASE_PATH: str = os.environ.get("OUTPUT_DATABASE_PATH", "photo_descriptions.json")
EMBEDDED_CACHE_FILE: str = os.environ.get("EMBEDDED_CACHE_PATH", "embedded_photos_cache.txt")
EXIFTOOL_PATH: str = os.environ.get("EXIFTOOL_PATH", "exiftool")
CHUNK_SIZE: int = int(os.environ.get("CHUNK_SIZE", "200"))
MAX_WORKERS: int = int(os.environ.get("MAX_WORKERS", "16"))

# PICTURE_DIRECTORIES can be configured as a comma-separated list of roots
_raw_dirs: str = os.environ.get("PICTURE_DIRECTORIES", "")
PICTURE_DIRS: List[str] = [d.strip() for d in _raw_dirs.split(",") if d.strip()]

# Type alias for JSON database entry dictionary
JSONEntry = Dict[str, Union[str, List[str], None]]

cache_lock: threading.Lock = threading.Lock()


def get_relative_path(full_path: str, scan_dirs: List[str]) -> str:
    """Extracts a relative path portion against any matching scan directory root.

    This ensures path matching is independent of absolute parent directories.

    Args:
        full_path: Absolute path to the file.
        scan_dirs: List of base directories to compute relative paths against.

    Returns:
        The normalized lowercase relative path with forward slashes.
    """
    normalized_path: str = full_path.replace("\\", "/").lower()
    for directory in scan_dirs:
        norm_dir: str = os.path.abspath(directory).replace("\\", "/").lower()
        if not norm_dir.endswith("/"):
            norm_dir += "/"
        if normalized_path.startswith(norm_dir):
            return normalized_path[len(norm_dir):]
    return os.path.basename(normalized_path)


def load_embedded_cache(scan_dirs: List[str]) -> Set[str]:
    """Loads previously embedded photos from cache file to avoid reprocessing.

    Reads paths, normalizes them, and returns them as a set of relative keys.

    Args:
        scan_dirs: List of directories to compute relative paths against.

    Returns:
        A set of lowercased, normalized relative path strings.
    """
    if not os.path.exists(EMBEDDED_CACHE_FILE):
        return set()
    cache_set: Set[str] = set()
    with open(EMBEDDED_CACHE_FILE, 'r', encoding='utf-8') as f:
        for line in f:
            stripped: str = line.strip()
            if stripped:
                rel_path: str = get_relative_path(stripped, scan_dirs)
                cache_set.add(rel_path)
    return cache_set


def save_to_cache(file_path: str) -> None:
    """Appends a processed file path to the embedded cache file.

    Uses a thread lock to ensure safe concurrent access from multiple workers.

    Args:
        file_path: The absolute path of the processed photo file.

    Returns:
        None
    """
    with cache_lock:
        with open(EMBEDDED_CACHE_FILE, 'a', encoding='utf-8') as f:
            f.write(file_path + '\n')


def update_metadata_single(entry: JSONEntry) -> None:
    """Processes one file at a time to update its EXIF metadata tags.

    Writes the description to IPTC, EXIF, and XMP fields, and handles common ExifTool errors.

    Args:
        entry: A dictionary containing the photo metadata fields.

    Returns:
        None
    """
    file_path: Optional[Union[str, List[str], None]] = entry.get('full_path')
    if not isinstance(file_path, str) or not file_path:
        return
        
    description_val: Optional[Union[str, List[str], None]] = entry.get('description') or entry.get('primary_subject')
    description: str = str(description_val) if description_val is not None else ""

    if os.path.exists(file_path):
        # Create a unique temporary argfile in the directory of the database to handle Unicode characters on Windows
        db_dir: str = os.path.dirname(os.path.abspath(OUTPUT_DATABASE_PATH))
        arg_file_path: str = os.path.join(db_dir, f"exif_args_{uuid.uuid4().hex}.txt")
        
        with open(arg_file_path, "w", encoding="utf-8") as arg_f:
            arg_f.write(file_path + "\n")
            
        cmd: List[str] = [
            EXIFTOOL_PATH,
            '-m', 
            '-charset', 'iptc=UTF8',
            '-charset', 'UTF8',      
            '-charset', 'filename=utf8',
            '-overwrite_original',
            f'-Caption-Abstract={description}',
            f'-Description={description}',
            f'-ImageDescription={description}',
            '-@', arg_file_path
        ]
        
        try:
            try:
                subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
                print(f"Updated (Single): {file_path}")
                save_to_cache(file_path)
            except subprocess.CalledProcessError as e:
                err_msg: str = e.stderr.decode('utf-8', errors='replace').strip() if e.stderr else str(e)
                
                if "Temporary file already exists" in err_msg:
                    tmp_file: str = file_path + "_exiftool_tmp"
                    if os.path.exists(tmp_file):
                        try:
                            os.remove(tmp_file)
                            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
                            print(f"Updated (Cleared TMP): {file_path}")
                            save_to_cache(file_path)
                        except Exception as retry_e:
                            print(f"Error updating {file_path} after clearing tmp: {retry_e}")
                elif "Bad Photoshop IRB resource" in err_msg:
                    try:
                        fallback_cmd: List[str] = cmd.copy()
                        fallback_cmd.insert(4, "-Photoshop:All=")
                        subprocess.run(fallback_cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
                        print(f"Updated (w/ IRB Fix): {file_path}")
                        save_to_cache(file_path)
                    except subprocess.CalledProcessError as e2:
                        err_msg2: str = e2.stderr.decode('utf-8', errors='replace').strip() if e2.stderr else str(e2)
                        print(f"Error updating {file_path} (even with IRB fix): {err_msg2}")
                elif "Not a valid HEIC" in err_msg or "looks more like a JPEG" in err_msg:
                    print(f"Skipped {file_path}: Extension mismatch (.HEIC but actually JPEG).")
                    save_to_cache(file_path)
                elif "Format error in file" in err_msg:
                    print(f"Skipped {file_path}: File is corrupted or unreadable.")
                    save_to_cache(file_path)
                else:
                    print(f"Error updating {file_path}: {err_msg}")
            except FileNotFoundError:
                print("Error: exiftool not found. Please ensure it is installed and in your system PATH or environment configuration.")
        finally:
            if os.path.exists(arg_file_path):
                try: 
                    os.remove(arg_file_path)
                except Exception: 
                    pass
    else:
        print(f"File not found: {file_path}")


def process_batch(chunk: List[JSONEntry], batch_idx: int) -> None:
    """Processes a list chunk of files using a single optimized ExifTool invocation.

    Validates paths, formats input JSON for batch update, and falls
    back to single file updates if an error occurs.

    Args:
        chunk: The list of JSON entries to process.
        batch_idx: The batch sequence index.

    Returns:
        None
    """
    valid_photos: List[Tuple[JSONEntry, str]] = []
    for entry in chunk:
        file_path: Optional[Union[str, List[str], None]] = entry.get('full_path')
        if not isinstance(file_path, str) or not file_path:
            continue
        if os.path.exists(file_path):
            valid_photos.append((entry, file_path))
        else:
            print(f"File not found: {file_path}")
            
    if not valid_photos:
        return
        
    uid: str = uuid.uuid4().hex
    db_dir: str = os.path.dirname(os.path.abspath(OUTPUT_DATABASE_PATH))
    import_json: str = os.path.join(db_dir, f"batch_import_{uid}.json")
    filelist_txt: str = os.path.join(db_dir, f"batch_files_{uid}.txt")
    
    json_data: List[Dict[str, str]] = []
    try:
        with open(filelist_txt, "w", encoding="utf-8") as f_txt:
            for entry, fp in valid_photos:
                description_val: Optional[Union[str, List[str], None]] = entry.get('description') or entry.get('primary_subject')
                desc: str = str(description_val) if description_val is not None else ""
                source_file: str = fp.replace("\\", "/")
                
                json_data.append({
                    "SourceFile": source_file,
                    "Caption-Abstract": desc,
                    "Description": desc,
                    "ImageDescription": desc
                })
                f_txt.write(source_file + "\n")
                
        with open(import_json, "w", encoding="utf-8") as f_json:
            json.dump(json_data, f_json, indent=2)
            
        cmd: List[str] = [
            EXIFTOOL_PATH,
            '-m',
            '-charset', 'filename=utf8',
            '-charset', 'iptc=UTF8',
            '-charset', 'UTF8',
            '-overwrite_original',
            f'-j={import_json}',
            '-@', filelist_txt
        ]
        
        result: subprocess.CompletedProcess[bytes] = subprocess.run(cmd, capture_output=True)
        stderr_output: str = result.stderr.decode('utf-8', errors='replace').lower() if result.stderr else ""
        
        for entry, fp in valid_photos:
            basename: str = os.path.basename(fp).lower()
            if basename in stderr_output or "error" in stderr_output:
                update_metadata_single(entry)
            else:
                save_to_cache(fp)
                    
        print(f"Processed Batch {batch_idx + 1} ({len(valid_photos)} photos)")
                    
    except Exception as e:
        print(f"Error running batch {batch_idx + 1}: {e}")
        # Fallback to single processing
        for entry, fp in valid_photos:
            update_metadata_single(entry)
            
    finally:
        if os.path.exists(import_json):
            try: 
                os.remove(import_json)
            except Exception: 
                pass
        if os.path.exists(filelist_txt):
            try: 
                os.remove(filelist_txt)
            except Exception: 
                pass


def main() -> None:
    """Main orchestrator function for the metadata embedding script.

    Loads the database JSON, filters out already embedded files using the cache,
    and runs multi-threaded chunk processing.

    Args:
        None

    Returns:
        None
    """
    if not os.path.exists(OUTPUT_DATABASE_PATH):
        print(f"Error: {OUTPUT_DATABASE_PATH} does not exist.")
        return

    with open(OUTPUT_DATABASE_PATH, 'r', encoding='utf-8') as f:
        photo_data: List[JSONEntry] = json.load(f)

    embedded_paths_lower: Set[str] = load_embedded_cache(PICTURE_DIRS)
    
    unprocessed_photos: List[JSONEntry] = []
    skipped_count: int = 0
    for entry in photo_data:
        fp: Optional[Union[str, List[str], None]] = entry.get('full_path')
        if not isinstance(fp, str) or not fp:
            continue
            
        rel_path: str = get_relative_path(fp, PICTURE_DIRS)
        if rel_path in embedded_paths_lower:
            skipped_count += 1
        else:
            unprocessed_photos.append(entry)

    if skipped_count > 0:
        print(f"Skipping {skipped_count} photos that already have embedded metadata (found in cache).")

    if not unprocessed_photos:
        print("All described photos have already been embedded! Nothing left to do.")
        return

    # Chunk the photos into batches to maximize CPU/Disk efficiency
    chunks: List[List[JSONEntry]] = [
        unprocessed_photos[i:i + CHUNK_SIZE] for i in range(0, len(unprocessed_photos), CHUNK_SIZE)
    ]
    
    workers: int = min(MAX_WORKERS, len(chunks))
    if workers == 0:
        workers = 1
    
    print(f"Starting chunked metadata embedding: {len(unprocessed_photos)} photos across {len(chunks)} batches using {workers} concurrent workers...")
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
        futures = []
        for i, chunk in enumerate(chunks):
            futures.append(executor.submit(process_batch, chunk, i))
        concurrent.futures.wait(futures)

    print("Metadata embedding complete.")


if __name__ == "__main__":
    main()
